// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/go-chi/chi/v5"
	"github.com/google/wire"
	"github.com/joaolima7/maconaria_back-end/config"
	"github.com/joaolima7/maconaria_back-end/internal/data/repositories/acacia"
	"github.com/joaolima7/maconaria_back-end/internal/data/repositories/library"
	"github.com/joaolima7/maconaria_back-end/internal/data/repositories/post"
	"github.com/joaolima7/maconaria_back-end/internal/data/repositories/timeline"
	"github.com/joaolima7/maconaria_back-end/internal/data/repositories/user"
	"github.com/joaolima7/maconaria_back-end/internal/data/repositories/worker"
	acacia2 "github.com/joaolima7/maconaria_back-end/internal/domain/repositories/acacia"
	library2 "github.com/joaolima7/maconaria_back-end/internal/domain/repositories/library"
	"github.com/joaolima7/maconaria_back-end/internal/domain/repositories/post"
	timeline2 "github.com/joaolima7/maconaria_back-end/internal/domain/repositories/timeline"
	user2 "github.com/joaolima7/maconaria_back-end/internal/domain/repositories/user"
	worker2 "github.com/joaolima7/maconaria_back-end/internal/domain/repositories/worker"
	"github.com/joaolima7/maconaria_back-end/internal/domain/usecases/acacia_usecase"
	"github.com/joaolima7/maconaria_back-end/internal/domain/usecases/library_usecase"
	"github.com/joaolima7/maconaria_back-end/internal/domain/usecases/post_usecase"
	"github.com/joaolima7/maconaria_back-end/internal/domain/usecases/timeline_usecase"
	"github.com/joaolima7/maconaria_back-end/internal/domain/usecases/user_usecase"
	"github.com/joaolima7/maconaria_back-end/internal/domain/usecases/worker_usecase"
	"github.com/joaolima7/maconaria_back-end/internal/infra/database"
	"github.com/joaolima7/maconaria_back-end/internal/infra/web/auth"
	"github.com/joaolima7/maconaria_back-end/internal/infra/web/handlers"
	"github.com/joaolima7/maconaria_back-end/internal/infra/web/middlewares"
	"github.com/joaolima7/maconaria_back-end/internal/infra/web/routes"
	"github.com/joaolima7/maconaria_back-end/internal/infra/web/server"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, error) {
	db, err := database.ProvideDatabase(cfg)
	if err != nil {
		return nil, err
	}
	queries := database.ProvideQueries(db)
	createUserRepositoryImpl := user.NewCreateUserRepositoryImpl(queries)
	createUserUseCase := user_usecase.NewCreateUserUseCase(createUserRepositoryImpl)
	getAllUsersRepositoryImpl := user.NewGetAllUsersRepositoryImpl(queries)
	getAllUsersUseCase := user_usecase.NewGetAllUsersUseCase(getAllUsersRepositoryImpl)
	updateUserByIDRepositoryImpl := user.NewUpdateUserByIDRepositoryImpl(queries)
	updateUserByIdUseCase := user_usecase.NewUpdateUserByIdUseCase(updateUserByIDRepositoryImpl)
	updateUserPasswordRepositoryImpl := user.NewUpdateUserPasswordRepositoryImpl(queries)
	getUserByIdRepositoryImpl := user.NewGetUserByIdRepositoryImpl(queries)
	updateUserPasswordUseCase := user_usecase.NewUpdateUserPasswordUseCase(updateUserPasswordRepositoryImpl, getUserByIdRepositoryImpl)
	getUserByIdUseCase := user_usecase.NewGetUserByIdUseCase(getUserByIdRepositoryImpl)
	userHandler := handlers.NewUserHandler(createUserUseCase, getAllUsersUseCase, updateUserByIdUseCase, updateUserPasswordUseCase, getUserByIdUseCase)
	getUserByEmailRepositoryImpl := user.NewGetUserByEmailRepositoryImpl(queries)
	jwtService := provideJWTService(cfg)
	loginUseCase := user_usecase.NewLoginUseCase(getUserByEmailRepositoryImpl, jwtService)
	authHandler := handlers.NewAuthHandler(loginUseCase)
	postImageRepositoryImpl := post.NewPostImageRepositoryImpl(queries)
	createPostRepositoryImpl := post.NewCreatePostRepositoryImpl(queries, postImageRepositoryImpl)
	createPostUseCase := post_usecase.NewCreatePostUseCase(createPostRepositoryImpl, getUserByIdRepositoryImpl)
	getAllPostsRepositoryImpl := post.NewGetAllPostsRepositoryImpl(queries, postImageRepositoryImpl)
	getAllPostsUseCase := post_usecase.NewGetAllPostsUseCase(getAllPostsRepositoryImpl)
	updatePostByIDRepositoryImpl := post.NewUpdatePostByIDRepositoryImpl(queries, postImageRepositoryImpl)
	updatePostByIDUseCase := post_usecase.NewUpdatePostByIDUseCase(updatePostByIDRepositoryImpl)
	deletePostRepositoryImpl := post.NewDeletePostRepositoryImpl(queries)
	deletePostUseCase := post_usecase.NewDeletePostUseCase(deletePostRepositoryImpl)
	postHandler := handlers.NewPostHandler(createPostUseCase, getAllPostsUseCase, updatePostByIDUseCase, deletePostUseCase)
	createWorkerRepositoryImpl := worker.NewCreateWorkerRepositoryImpl(queries)
	createWorkerUseCase := worker_usecase.NewCreateWorkerUseCase(createWorkerRepositoryImpl)
	getAllWorkersRepositoryImpl := worker.NewGetAllWorkersRepositoryImpl(queries)
	getAllWorkersUseCase := worker_usecase.NewGetAllWorkersUseCase(getAllWorkersRepositoryImpl)
	getWorkerByIDRepositoryImpl := worker.NewGetWorkerByIDRepositoryImpl(queries)
	getWorkerByIDUseCase := worker_usecase.NewGetWorkerByIDUseCase(getWorkerByIDRepositoryImpl)
	updateWorkerByIDRepositoryImpl := worker.NewUpdateWorkerByIDRepositoryImpl(queries)
	updateWorkerByIDUseCase := worker_usecase.NewUpdateWorkerByIDUseCase(updateWorkerByIDRepositoryImpl)
	deleteWorkerRepositoryImpl := worker.NewDeleteWorkerRepositoryImpl(queries)
	deleteWorkerUseCase := worker_usecase.NewDeleteWorkerUseCase(deleteWorkerRepositoryImpl)
	workerHandler := handlers.NewWorkerHandler(createWorkerUseCase, getAllWorkersUseCase, getWorkerByIDUseCase, updateWorkerByIDUseCase, deleteWorkerUseCase)
	createTimelineRepositoryImpl := timeline.NewCreateTimelineRepositoryImpl(queries)
	createTimelineUseCase := timeline_usecase.NewCreateTimelineUseCase(createTimelineRepositoryImpl)
	getAllTimelinesRepositoryImpl := timeline.NewGetAllTimelinesRepositoryImpl(queries)
	getAllTimelinesUseCase := timeline_usecase.NewGetAllTimelinesUseCase(getAllTimelinesRepositoryImpl)
	getTimelineByIDRepositoryImpl := timeline.NewGetTimelineByIDRepositoryImpl(queries)
	getTimelineByIDUseCase := timeline_usecase.NewGetTimelineByIDUseCase(getTimelineByIDRepositoryImpl)
	updateTimelineByIDRepositoryImpl := timeline.NewUpdateTimelineByIDRepositoryImpl(queries)
	updateTimelineByIDUseCase := timeline_usecase.NewUpdateTimelineByIDUseCase(updateTimelineByIDRepositoryImpl)
	deleteTimelineRepositoryImpl := timeline.NewDeleteTimelineRepositoryImpl(queries)
	deleteTimelineUseCase := timeline_usecase.NewDeleteTimelineUseCase(deleteTimelineRepositoryImpl)
	timelineHandler := handlers.NewTimelineHandler(createTimelineUseCase, getAllTimelinesUseCase, getTimelineByIDUseCase, updateTimelineByIDUseCase, deleteTimelineUseCase)
	createAcaciaRepositoryImpl := acacia.NewCreateAcaciaRepositoryImpl(queries)
	createAcaciaUseCase := acacia_usecase.NewCreateAcaciaUseCase(createAcaciaRepositoryImpl)
	getAllAcaciasRepositoryImpl := acacia.NewGetAllAcaciasRepositoryImpl(queries)
	getAllAcaciasUseCase := acacia_usecase.NewGetAllAcaciasUseCase(getAllAcaciasRepositoryImpl)
	getAcaciaByIDRepositoryImpl := acacia.NewGetAcaciaByIDRepositoryImpl(queries)
	getAcaciaByIDUseCase := acacia_usecase.NewGetAcaciaByIDUseCase(getAcaciaByIDRepositoryImpl)
	updateAcaciaByIDRepositoryImpl := acacia.NewUpdateAcaciaByIDRepositoryImpl(queries)
	updateAcaciaByIDUseCase := acacia_usecase.NewUpdateAcaciaByIDUseCase(updateAcaciaByIDRepositoryImpl)
	deleteAcaciaRepositoryImpl := acacia.NewDeleteAcaciaRepositoryImpl(queries)
	deleteAcaciaUseCase := acacia_usecase.NewDeleteAcaciaUseCase(deleteAcaciaRepositoryImpl)
	acaciaHandler := handlers.NewAcaciaHandler(createAcaciaUseCase, getAllAcaciasUseCase, getAcaciaByIDUseCase, updateAcaciaByIDUseCase, deleteAcaciaUseCase)
	createLibraryRepositoryImpl := library.NewCreateLibraryRepositoryImpl(queries)
	createLibraryUseCase := library_usecase.NewCreateLibraryUseCase(createLibraryRepositoryImpl)
	getAllLibrariesRepositoryImpl := library.NewGetAllLibrariesRepositoryImpl(queries)
	getAllLibrariesUseCase := library_usecase.NewGetAllLibrariesUseCase(getAllLibrariesRepositoryImpl)
	getLibraryByIDRepositoryImpl := library.NewGetLibraryByIDRepositoryImpl(queries)
	getLibraryByIDUseCase := library_usecase.NewGetLibraryByIDUseCase(getLibraryByIDRepositoryImpl)
	getLibrariesByDegreeRepositoryImpl := library.NewGetLibrariesByDegreeRepositoryImpl(queries)
	getLibrariesByDegreeUseCase := library_usecase.NewGetLibrariesByDegreeUseCase(getLibrariesByDegreeRepositoryImpl)
	updateLibraryByIDRepositoryImpl := library.NewUpdateLibraryByIDRepositoryImpl(queries)
	updateLibraryByIDUseCase := library_usecase.NewUpdateLibraryByIDUseCase(updateLibraryByIDRepositoryImpl)
	deleteLibraryRepositoryImpl := library.NewDeleteLibraryRepositoryImpl(queries)
	deleteLibraryUseCase := library_usecase.NewDeleteLibraryUseCase(deleteLibraryRepositoryImpl)
	libraryHandler := handlers.NewLibraryHandler(createLibraryUseCase, getAllLibrariesUseCase, getLibraryByIDUseCase, getLibrariesByDegreeUseCase, updateLibraryByIDUseCase, deleteLibraryUseCase)
	healthHandler := handlers.NewHealthHandler(db)
	authMiddleware := middlewares.NewAuthMiddleware(jwtService)
	router := routes.NewRouter(userHandler, authHandler, postHandler, workerHandler, timelineHandler, acaciaHandler, libraryHandler, healthHandler, authMiddleware)
	mux := provideChiRouter(router)
	server := provideServer(mux, cfg)
	app := &App{
		Server: server,
		DB:     db,
	}
	return app, nil
}

// wire.go:

// User Repository Set
var UserRepositorySet = wire.NewSet(user.NewCreateUserRepositoryImpl, wire.Bind(new(user2.CreateUserRepository), new(*user.CreateUserRepositoryImpl)), user.NewGetAllUsersRepositoryImpl, wire.Bind(new(user2.GetAllUsersRepository), new(*user.GetAllUsersRepositoryImpl)), user.NewGetUserByEmailRepositoryImpl, wire.Bind(new(user2.GetUserByEmailRepository), new(*user.GetUserByEmailRepositoryImpl)), user.NewGetUserByIdRepositoryImpl, wire.Bind(new(user2.GetUserByIdRepository), new(*user.GetUserByIdRepositoryImpl)), user.NewGetUserByCIMRepositoryImpl, wire.Bind(new(user2.GetUserByCIMRepository), new(*user.GetUserByCIMRepositoryImpl)), user.NewUpdateUserByIDRepositoryImpl, wire.Bind(new(user2.UpdateUserByIDRepository), new(*user.UpdateUserByIDRepositoryImpl)), user.NewUpdateUserPasswordRepositoryImpl, wire.Bind(new(user2.UpdateUserPasswordRepository), new(*user.UpdateUserPasswordRepositoryImpl)))

// Post Repository Set
var PostRepositorySet = wire.NewSet(post.NewPostImageRepositoryImpl, wire.Bind(new(post_repository.PostImageRepository), new(*post.PostImageRepositoryImpl)), post.NewCreatePostRepositoryImpl, wire.Bind(new(post_repository.CreatePostRepository), new(*post.CreatePostRepositoryImpl)), post.NewGetAllPostsRepositoryImpl, wire.Bind(new(post_repository.GetAllPostsRepository), new(*post.GetAllPostsRepositoryImpl)), post.NewUpdatePostByIDRepositoryImpl, wire.Bind(new(post_repository.UpdatePostByIDRepository), new(*post.UpdatePostByIDRepositoryImpl)), post.NewDeletePostRepositoryImpl, wire.Bind(new(post_repository.DeletePostRepository), new(*post.DeletePostRepositoryImpl)))

// Worker Repository Set
var WorkerRepositorySet = wire.NewSet(worker.NewCreateWorkerRepositoryImpl, wire.Bind(new(worker2.CreateWorkerRepository), new(*worker.CreateWorkerRepositoryImpl)), worker.NewGetAllWorkersRepositoryImpl, wire.Bind(new(worker2.GetAllWorkersRepository), new(*worker.GetAllWorkersRepositoryImpl)), worker.NewGetWorkerByIDRepositoryImpl, wire.Bind(new(worker2.GetWorkerByIDRepository), new(*worker.GetWorkerByIDRepositoryImpl)), worker.NewUpdateWorkerByIDRepositoryImpl, wire.Bind(new(worker2.UpdateWorkerByIDRepository), new(*worker.UpdateWorkerByIDRepositoryImpl)), worker.NewDeleteWorkerRepositoryImpl, wire.Bind(new(worker2.DeleteWorkerRepository), new(*worker.DeleteWorkerRepositoryImpl)))

// Timeline Repository Set
var TimelineRepositorySet = wire.NewSet(timeline.NewCreateTimelineRepositoryImpl, wire.Bind(new(timeline2.CreateTimelineRepository), new(*timeline.CreateTimelineRepositoryImpl)), timeline.NewGetAllTimelinesRepositoryImpl, wire.Bind(new(timeline2.GetAllTimelinesRepository), new(*timeline.GetAllTimelinesRepositoryImpl)), timeline.NewGetTimelineByIDRepositoryImpl, wire.Bind(new(timeline2.GetTimelineByIDRepository), new(*timeline.GetTimelineByIDRepositoryImpl)), timeline.NewUpdateTimelineByIDRepositoryImpl, wire.Bind(new(timeline2.UpdateTimelineByIDRepository), new(*timeline.UpdateTimelineByIDRepositoryImpl)), timeline.NewDeleteTimelineRepositoryImpl, wire.Bind(new(timeline2.DeleteTimelineRepository), new(*timeline.DeleteTimelineRepositoryImpl)))

// Acacia Repository Set
var AcaciaRepositorySet = wire.NewSet(acacia.NewCreateAcaciaRepositoryImpl, wire.Bind(new(acacia2.CreateAcaciaRepository), new(*acacia.CreateAcaciaRepositoryImpl)), acacia.NewGetAllAcaciasRepositoryImpl, wire.Bind(new(acacia2.GetAllAcaciasRepository), new(*acacia.GetAllAcaciasRepositoryImpl)), acacia.NewGetAcaciaByIDRepositoryImpl, wire.Bind(new(acacia2.GetAcaciaByIDRepository), new(*acacia.GetAcaciaByIDRepositoryImpl)), acacia.NewUpdateAcaciaByIDRepositoryImpl, wire.Bind(new(acacia2.UpdateAcaciaByIDRepository), new(*acacia.UpdateAcaciaByIDRepositoryImpl)), acacia.NewDeleteAcaciaRepositoryImpl, wire.Bind(new(acacia2.DeleteAcaciaRepository), new(*acacia.DeleteAcaciaRepositoryImpl)))

var LibraryRepositorySet = wire.NewSet(library.NewCreateLibraryRepositoryImpl, wire.Bind(new(library2.CreateLibraryRepository), new(*library.CreateLibraryRepositoryImpl)), library.NewGetAllLibrariesRepositoryImpl, wire.Bind(new(library2.GetAllLibrariesRepository), new(*library.GetAllLibrariesRepositoryImpl)), library.NewGetLibraryByIDRepositoryImpl, wire.Bind(new(library2.GetLibraryByIDRepository), new(*library.GetLibraryByIDRepositoryImpl)), library.NewGetLibrariesByDegreeRepositoryImpl, wire.Bind(new(library2.GetLibrariesByDegreeRepository), new(*library.GetLibrariesByDegreeRepositoryImpl)), library.NewUpdateLibraryByIDRepositoryImpl, wire.Bind(new(library2.UpdateLibraryByIDRepository), new(*library.UpdateLibraryByIDRepositoryImpl)), library.NewDeleteLibraryRepositoryImpl, wire.Bind(new(library2.DeleteLibraryRepository), new(*library.DeleteLibraryRepositoryImpl)))

// User UseCase Set
var UserUseCaseSet = wire.NewSet(user_usecase.NewCreateUserUseCase, user_usecase.NewGetAllUsersUseCase, user_usecase.NewGetUserByIdUseCase, user_usecase.NewUpdateUserByIdUseCase, user_usecase.NewUpdateUserPasswordUseCase, user_usecase.NewLoginUseCase)

// Post UseCase Set
var PostUseCaseSet = wire.NewSet(post_usecase.NewCreatePostUseCase, post_usecase.NewGetAllPostsUseCase, post_usecase.NewUpdatePostByIDUseCase, post_usecase.NewDeletePostUseCase)

// Worker UseCase Set
var WorkerUseCaseSet = wire.NewSet(worker_usecase.NewCreateWorkerUseCase, worker_usecase.NewGetAllWorkersUseCase, worker_usecase.NewGetWorkerByIDUseCase, worker_usecase.NewUpdateWorkerByIDUseCase, worker_usecase.NewDeleteWorkerUseCase)

// Timeline UseCase Set
var TimelineUseCaseSet = wire.NewSet(timeline_usecase.NewCreateTimelineUseCase, timeline_usecase.NewGetAllTimelinesUseCase, timeline_usecase.NewGetTimelineByIDUseCase, timeline_usecase.NewUpdateTimelineByIDUseCase, timeline_usecase.NewDeleteTimelineUseCase)

// Acacia UseCase Set
var AcaciaUseCaseSet = wire.NewSet(acacia_usecase.NewCreateAcaciaUseCase, acacia_usecase.NewGetAllAcaciasUseCase, acacia_usecase.NewGetAcaciaByIDUseCase, acacia_usecase.NewUpdateAcaciaByIDUseCase, acacia_usecase.NewDeleteAcaciaUseCase)

var LibraryUseCaseSet = wire.NewSet(library_usecase.NewCreateLibraryUseCase, library_usecase.NewGetAllLibrariesUseCase, library_usecase.NewGetLibraryByIDUseCase, library_usecase.NewGetLibrariesByDegreeUseCase, library_usecase.NewUpdateLibraryByIDUseCase, library_usecase.NewDeleteLibraryUseCase)

// Infra Set
var InfraSet = wire.NewSet(database.ProvideDatabase, database.ProvideQueries, provideJWTService)

// Web Set
var WebSet = wire.NewSet(handlers.NewUserHandler, handlers.NewAuthHandler, handlers.NewPostHandler, handlers.NewWorkerHandler, handlers.NewTimelineHandler, handlers.NewAcaciaHandler, handlers.NewLibraryHandler, handlers.NewHealthHandler, middlewares.NewAuthMiddleware, routes.NewRouter, provideChiRouter,
	provideServer,
)

func provideJWTService(cfg *config.Config) *auth.JWTService {
	return auth.NewJWTService(cfg.JWTSecret, cfg.GetJWTDuration())
}

func provideChiRouter(router *routes.Router) *chi.Mux {
	return router.Setup()
}

func provideServer(router *chi.Mux, cfg *config.Config) *server.Server {
	return server.NewServer(router, cfg.ServerPort)
}

type App struct {
	Server *server.Server
	DB     *sql.DB
}

func (a *App) Cleanup() {
	if a.DB != nil {
		a.DB.Close()
	}
}
