// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/go-chi/chi/v5"
	"github.com/google/wire"
	"github.com/joaolima7/maconaria_back-end/config"
	"github.com/joaolima7/maconaria_back-end/internal/data/repositories/user"
	user2 "github.com/joaolima7/maconaria_back-end/internal/domain/repositories/user"
	"github.com/joaolima7/maconaria_back-end/internal/domain/usecases/user_usecase"
	"github.com/joaolima7/maconaria_back-end/internal/infra/database"
	"github.com/joaolima7/maconaria_back-end/internal/infra/web/auth"
	"github.com/joaolima7/maconaria_back-end/internal/infra/web/handlers"
	"github.com/joaolima7/maconaria_back-end/internal/infra/web/middlewares"
	"github.com/joaolima7/maconaria_back-end/internal/infra/web/routes"
	"github.com/joaolima7/maconaria_back-end/internal/infra/web/server"
)

// Injectors from wire.go:

// InitializeApp injeta todas as dependências e retorna App com cleanup
func InitializeApp(cfg *config.Config) (*App, error) {
	db, err := database.ProvideDatabase(cfg)
	if err != nil {
		return nil, err
	}
	queries := database.ProvideQueries(db)
	createUserRepositoryImpl := user.NewCreateUserRepositoryImpl(queries)
	createUserUseCase := user_usecase.NewCreateUserUseCase(createUserRepositoryImpl)
	getAllUsersRepositoryImpl := user.NewGetAllUsersRepositoryImpl(queries)
	getAllUsersUseCase := user_usecase.NewGetAllUsersUseCase(getAllUsersRepositoryImpl)
	updateUserByIDRepositoryImpl := user.NewUpdateUserByIDRepositoryImpl(queries)
	updateUserByIdUseCase := user_usecase.NewUpdateUserByIdUseCase(updateUserByIDRepositoryImpl)
	updateUserPasswordRepositoryImpl := user.NewUpdateUserPasswordRepositoryImpl(queries)
	getUserByIdRepositoryImpl := user.NewGetUserByIdRepositoryImpl(queries)
	updateUserPasswordUseCase := user_usecase.NewUpdateUserPasswordUseCase(updateUserPasswordRepositoryImpl, getUserByIdRepositoryImpl)
	getUserByIdUseCase := user_usecase.NewGetUserByIdUseCase(getUserByIdRepositoryImpl)
	userHandler := handlers.NewUserHandler(createUserUseCase, getAllUsersUseCase, updateUserByIdUseCase, updateUserPasswordUseCase, getUserByIdUseCase)
	getUserByEmailRepositoryImpl := user.NewGetUserByEmailRepositoryImpl(queries)
	jwtService := provideJWTService(cfg)
	loginUseCase := user_usecase.NewLoginUseCase(getUserByEmailRepositoryImpl, jwtService)
	authHandler := handlers.NewAuthHandler(loginUseCase)
	healthHandler := handlers.NewHealthHandler(db)
	authMiddleware := middlewares.NewAuthMiddleware(jwtService)
	router := routes.NewRouter(userHandler, authHandler, healthHandler, authMiddleware)
	mux := provideChiRouter(router)
	server := provideServer(mux, cfg)
	app := &App{
		Server: server,
		DB:     db,
	}
	return app, nil
}

// wire.go:

// UserRepositorySet agrupa todos os providers de repositórios de user
var UserRepositorySet = wire.NewSet(user.NewCreateUserRepositoryImpl, wire.Bind(new(user2.CreateUserRepository), new(*user.CreateUserRepositoryImpl)), user.NewGetAllUsersRepositoryImpl, wire.Bind(new(user2.GetAllUsersRepository), new(*user.GetAllUsersRepositoryImpl)), user.NewGetUserByEmailRepositoryImpl, wire.Bind(new(user2.GetUserByEmailRepository), new(*user.GetUserByEmailRepositoryImpl)), user.NewUpdateUserByIDRepositoryImpl, wire.Bind(new(user2.UpdateUserByIDRepository), new(*user.UpdateUserByIDRepositoryImpl)), user.NewUpdateUserPasswordRepositoryImpl, wire.Bind(new(user2.UpdateUserPasswordRepository), new(*user.UpdateUserPasswordRepositoryImpl)), user.NewGetUserByIdRepositoryImpl, wire.Bind(new(user2.GetUserByIdRepository), new(*user.GetUserByIdRepositoryImpl)))

// UserUseCaseSet agrupa todos os use cases de user
var UserUseCaseSet = wire.NewSet(user_usecase.NewCreateUserUseCase, user_usecase.NewGetAllUsersUseCase, user_usecase.NewUpdateUserByIdUseCase, user_usecase.NewUpdateUserPasswordUseCase, user_usecase.NewGetUserByIdUseCase, user_usecase.NewLoginUseCase)

// InfraSet agrupa providers de infraestrutura
var InfraSet = wire.NewSet(database.ProvideDatabase, database.ProvideQueries, provideJWTService)

// WebSet agrupa providers da camada web
var WebSet = wire.NewSet(handlers.NewUserHandler, handlers.NewAuthHandler, handlers.NewHealthHandler, middlewares.NewAuthMiddleware, routes.NewRouter, provideChiRouter,
	provideServer,
)

// provideJWTService cria instância do serviço JWT
func provideJWTService(cfg *config.Config) *auth.JWTService {
	return auth.NewJWTService(cfg.JWTSecret, cfg.GetJWTDuration())
}

// provideChiRouter configura o router Chi
func provideChiRouter(router *routes.Router) *chi.Mux {
	return router.Setup()
}

// provideServer cria instância do servidor
func provideServer(router *chi.Mux, cfg *config.Config) *server.Server {
	return server.NewServer(router, cfg.ServerPort)
}

// App agrupa servidor e banco para gerenciar ciclo de vida
type App struct {
	Server *server.Server
	DB     *sql.DB
}

// Cleanup fecha a conexão do banco
func (a *App) Cleanup() {
	if a.DB != nil {
		a.DB.Close()
	}
}
