// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: acacia_queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createAcacia = `-- name: CreateAcacia :execresult
INSERT INTO acacias (id, name, terms, is_president, deceased, image_url)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAcaciaParams struct {
	ID          string
	Name        string
	Terms       json.RawMessage
	IsPresident bool
	Deceased    bool
	ImageUrl    string
}

func (q *Queries) CreateAcacia(ctx context.Context, arg CreateAcaciaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAcacia,
		arg.ID,
		arg.Name,
		arg.Terms,
		arg.IsPresident,
		arg.Deceased,
		arg.ImageUrl,
	)
}

const deleteAcacia = `-- name: DeleteAcacia :exec
DELETE FROM acacias WHERE id = ?
`

func (q *Queries) DeleteAcacia(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAcacia, id)
	return err
}

const getAcaciaByID = `-- name: GetAcaciaByID :one
SELECT id, name, terms, is_president, deceased, image_url, created_at, updated_at
FROM acacias
WHERE id = ?
`

func (q *Queries) GetAcaciaByID(ctx context.Context, id string) (Acacia, error) {
	row := q.db.QueryRowContext(ctx, getAcaciaByID, id)
	var i Acacia
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Terms,
		&i.IsPresident,
		&i.Deceased,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAcaciaByName = `-- name: GetAcaciaByName :one
SELECT id, name, terms, is_president, deceased, image_url, created_at, updated_at
FROM acacias
WHERE name = ?
`

func (q *Queries) GetAcaciaByName(ctx context.Context, name string) (Acacia, error) {
	row := q.db.QueryRowContext(ctx, getAcaciaByName, name)
	var i Acacia
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Terms,
		&i.IsPresident,
		&i.Deceased,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllAcacias = `-- name: GetAllAcacias :many
SELECT id, name, terms, is_president, deceased, image_url, created_at, updated_at
FROM acacias
ORDER BY name ASC
`

func (q *Queries) GetAllAcacias(ctx context.Context) ([]Acacia, error) {
	rows, err := q.db.QueryContext(ctx, getAllAcacias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Acacia
	for rows.Next() {
		var i Acacia
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Terms,
			&i.IsPresident,
			&i.Deceased,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAcacia = `-- name: UpdateAcacia :execresult
UPDATE acacias
SET name = ?, terms = ?, is_president = ?, deceased = ?, image_url = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateAcaciaParams struct {
	Name        string
	Terms       json.RawMessage
	IsPresident bool
	Deceased    bool
	ImageUrl    string
	ID          string
}

func (q *Queries) UpdateAcacia(ctx context.Context, arg UpdateAcaciaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAcacia,
		arg.Name,
		arg.Terms,
		arg.IsPresident,
		arg.Deceased,
		arg.ImageUrl,
		arg.ID,
	)
}
