// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: library_queries.sql

package db

import (
	"context"
	"database/sql"
)

const createLibrary = `-- name: CreateLibrary :execresult
INSERT INTO libraries (id, title, small_description, degree, file_url, cover_url, link)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateLibraryParams struct {
	ID               string
	Title            string
	SmallDescription string
	Degree           LibrariesDegree
	FileUrl          sql.NullString
	CoverUrl         sql.NullString
	Link             sql.NullString
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLibrary,
		arg.ID,
		arg.Title,
		arg.SmallDescription,
		arg.Degree,
		arg.FileUrl,
		arg.CoverUrl,
		arg.Link,
	)
}

const deleteLibrary = `-- name: DeleteLibrary :exec
DELETE FROM libraries WHERE id = ?
`

func (q *Queries) DeleteLibrary(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLibrary, id)
	return err
}

const getAllLibraries = `-- name: GetAllLibraries :many
SELECT id, title, small_description, degree, file_url, cover_url, link, created_at, updated_at
FROM libraries
ORDER BY created_at DESC
`

func (q *Queries) GetAllLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, getAllLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SmallDescription,
			&i.Degree,
			&i.FileUrl,
			&i.CoverUrl,
			&i.Link,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLibrariesByDegree = `-- name: GetLibrariesByDegree :many
SELECT id, title, small_description, degree, file_url, cover_url, link, created_at, updated_at
FROM libraries
WHERE degree = ?
ORDER BY created_at DESC
`

func (q *Queries) GetLibrariesByDegree(ctx context.Context, degree LibrariesDegree) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, getLibrariesByDegree, degree)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SmallDescription,
			&i.Degree,
			&i.FileUrl,
			&i.CoverUrl,
			&i.Link,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLibraryByID = `-- name: GetLibraryByID :one
SELECT id, title, small_description, degree, file_url, cover_url, link, created_at, updated_at
FROM libraries
WHERE id = ?
`

func (q *Queries) GetLibraryByID(ctx context.Context, id string) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibraryByID, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SmallDescription,
		&i.Degree,
		&i.FileUrl,
		&i.CoverUrl,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLibraryByTitle = `-- name: GetLibraryByTitle :one
SELECT id, title, small_description, degree, file_url, cover_url, link, created_at, updated_at
FROM libraries
WHERE title = ?
`

func (q *Queries) GetLibraryByTitle(ctx context.Context, title string) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibraryByTitle, title)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SmallDescription,
		&i.Degree,
		&i.FileUrl,
		&i.CoverUrl,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLibrary = `-- name: UpdateLibrary :execresult
UPDATE libraries
SET title = ?, small_description = ?, degree = ?, file_url = ?, cover_url = ?, link = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateLibraryParams struct {
	Title            string
	SmallDescription string
	Degree           LibrariesDegree
	FileUrl          sql.NullString
	CoverUrl         sql.NullString
	Link             sql.NullString
	ID               string
}

func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateLibrary,
		arg.Title,
		arg.SmallDescription,
		arg.Degree,
		arg.FileUrl,
		arg.CoverUrl,
		arg.Link,
		arg.ID,
	)
}
