// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type LibrariesDegree string

const (
	LibrariesDegreeApprentice LibrariesDegree = "apprentice"
	LibrariesDegreeCompanion  LibrariesDegree = "companion"
	LibrariesDegreeMaster     LibrariesDegree = "master"
)

func (e *LibrariesDegree) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LibrariesDegree(s)
	case string:
		*e = LibrariesDegree(s)
	default:
		return fmt.Errorf("unsupported scan type for LibrariesDegree: %T", src)
	}
	return nil
}

type NullLibrariesDegree struct {
	LibrariesDegree LibrariesDegree
	Valid           bool // Valid is true if LibrariesDegree is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLibrariesDegree) Scan(value interface{}) error {
	if value == nil {
		ns.LibrariesDegree, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LibrariesDegree.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLibrariesDegree) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LibrariesDegree), nil
}

type PostsPostType string

const (
	PostsPostTypeEvent         PostsPostType = "event"
	PostsPostTypeCommemoration PostsPostType = "commemoration"
	PostsPostTypeArticle       PostsPostType = "article"
	PostsPostTypeNews          PostsPostType = "news"
)

func (e *PostsPostType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostsPostType(s)
	case string:
		*e = PostsPostType(s)
	default:
		return fmt.Errorf("unsupported scan type for PostsPostType: %T", src)
	}
	return nil
}

type NullPostsPostType struct {
	PostsPostType PostsPostType
	Valid         bool // Valid is true if PostsPostType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostsPostType) Scan(value interface{}) error {
	if value == nil {
		ns.PostsPostType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostsPostType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostsPostType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostsPostType), nil
}

type UsersDegree string

const (
	UsersDegreeApprentice UsersDegree = "apprentice"
	UsersDegreeCompanion  UsersDegree = "companion"
	UsersDegreeMaster     UsersDegree = "master"
)

func (e *UsersDegree) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersDegree(s)
	case string:
		*e = UsersDegree(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersDegree: %T", src)
	}
	return nil
}

type NullUsersDegree struct {
	UsersDegree UsersDegree
	Valid       bool // Valid is true if UsersDegree is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersDegree) Scan(value interface{}) error {
	if value == nil {
		ns.UsersDegree, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersDegree.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersDegree) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersDegree), nil
}

type Acacia struct {
	ID          string
	Name        string
	Terms       json.RawMessage
	IsPresident bool
	Deceased    bool
	ImageUrl    string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Library struct {
	ID               string
	Title            string
	SmallDescription string
	Degree           LibrariesDegree
	FileUrl          sql.NullString
	CoverUrl         sql.NullString
	Link             sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type Post struct {
	ID                  string
	Title               string
	Category            string
	SmallDescription    string
	CompleteDescription string
	Date                sql.NullString
	Time                sql.NullString
	Location            sql.NullString
	IsFeatured          bool
	PostType            PostsPostType
	UserID              string
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

type PostImage struct {
	ID        string
	PostID    string
	ImageUrl  string
	CreatedAt sql.NullTime
}

type Timeline struct {
	ID          string
	Period      string
	PdfUrl      string
	IsHighlight bool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID        string
	Name      string
	Email     string
	Password  string
	IsActive  bool
	IsAdmin   bool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Cim       string
	Degree    UsersDegree
}

type Wordkey struct {
	ID        string
	Wordkey   string
	Active    bool
	CreatedAt sql.NullTime
}

type Worker struct {
	ID                string
	Number            int32
	Name              string
	Registration      string
	BirthDate         time.Time
	ImageUrl          string
	Deceased          bool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	InitiationDate    sql.NullTime
	ElevationDate     sql.NullTime
	ExaltationDate    sql.NullTime
	AffiliationDate   sql.NullTime
	InstallationDate  sql.NullTime
	EmeritusMasonDate sql.NullTime
	ProvectMasonDate  sql.NullTime
}
