// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	Date        time.Time
	Image       sql.NullString
	UserID      uuid.UUID
	PostType    interface{}
}

type User struct {
	ID       uuid.UUID
	Name     string
	Email    string
	Password string
	IsActive bool
	IsAdmin  bool
}
