// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post_images.sql

package db

import (
	"context"
	"database/sql"
)

const createPostImage = `-- name: CreatePostImage :execresult
INSERT INTO post_images (id, post_id, image_data)
VALUES (?, ?, ?)
`

type CreatePostImageParams struct {
	ID        string
	PostID    string
	ImageData []byte
}

func (q *Queries) CreatePostImage(ctx context.Context, arg CreatePostImageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPostImage, arg.ID, arg.PostID, arg.ImageData)
}

const deletePostImageByID = `-- name: DeletePostImageByID :exec
DELETE FROM post_images WHERE id = ?
`

func (q *Queries) DeletePostImageByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePostImageByID, id)
	return err
}

const deletePostImagesByPostID = `-- name: DeletePostImagesByPostID :exec
DELETE FROM post_images WHERE post_id = ?
`

func (q *Queries) DeletePostImagesByPostID(ctx context.Context, postID string) error {
	_, err := q.db.ExecContext(ctx, deletePostImagesByPostID, postID)
	return err
}

const getPostImageByID = `-- name: GetPostImageByID :one
SELECT id, post_id, image_data, created_at
FROM post_images
WHERE id = ?
`

func (q *Queries) GetPostImageByID(ctx context.Context, id string) (PostImage, error) {
	row := q.db.QueryRowContext(ctx, getPostImageByID, id)
	var i PostImage
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ImageData,
		&i.CreatedAt,
	)
	return i, err
}

const getPostImages = `-- name: GetPostImages :many
SELECT id, post_id, image_data, created_at
FROM post_images
WHERE post_id = ?
ORDER BY created_at
`

func (q *Queries) GetPostImages(ctx context.Context, postID string) ([]PostImage, error) {
	rows, err := q.db.QueryContext(ctx, getPostImages, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostImage
	for rows.Next() {
		var i PostImage
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ImageData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
