// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_queries.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (id, name, email, password, cim, degree, is_active, is_admin, is_regular)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID        string
	Name      string
	Email     string
	Password  string
	Cim       string
	Degree    UsersDegree
	IsActive  bool
	IsAdmin   bool
	IsRegular bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Cim,
		arg.Degree,
		arg.IsActive,
		arg.IsAdmin,
		arg.IsRegular,
	)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, email, password, cim, degree, is_active, is_admin, is_regular, created_at, updated_at FROM users
`

type GetAllUsersRow struct {
	ID        string
	Name      string
	Email     string
	Password  string
	Cim       string
	Degree    UsersDegree
	IsActive  bool
	IsAdmin   bool
	IsRegular bool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Cim,
			&i.Degree,
			&i.IsActive,
			&i.IsAdmin,
			&i.IsRegular,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByCIM = `-- name: GetUserByCIM :one
SELECT id, name, email, password, cim, degree, is_active, is_admin, is_regular, created_at, updated_at FROM users WHERE cim = ?
`

type GetUserByCIMRow struct {
	ID        string
	Name      string
	Email     string
	Password  string
	Cim       string
	Degree    UsersDegree
	IsActive  bool
	IsAdmin   bool
	IsRegular bool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetUserByCIM(ctx context.Context, cim string) (GetUserByCIMRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByCIM, cim)
	var i GetUserByCIMRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Cim,
		&i.Degree,
		&i.IsActive,
		&i.IsAdmin,
		&i.IsRegular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, cim, degree, is_active, is_admin, is_regular, created_at, updated_at FROM users WHERE email = ?
`

type GetUserByEmailRow struct {
	ID        string
	Name      string
	Email     string
	Password  string
	Cim       string
	Degree    UsersDegree
	IsActive  bool
	IsAdmin   bool
	IsRegular bool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Cim,
		&i.Degree,
		&i.IsActive,
		&i.IsAdmin,
		&i.IsRegular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password, cim, degree, is_active, is_admin, is_regular, created_at, updated_at FROM users WHERE id = ?
`

type GetUserByIDRow struct {
	ID        string
	Name      string
	Email     string
	Password  string
	Cim       string
	Degree    UsersDegree
	IsActive  bool
	IsAdmin   bool
	IsRegular bool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Cim,
		&i.Degree,
		&i.IsActive,
		&i.IsAdmin,
		&i.IsRegular,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users
SET name = ?, email = ?, cim = ?, degree = ?, is_active = ?, is_admin = ?, is_regular = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Name      string
	Email     string
	Cim       string
	Degree    UsersDegree
	IsActive  bool
	IsAdmin   bool
	IsRegular bool
	ID        string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Cim,
		arg.Degree,
		arg.IsActive,
		arg.IsAdmin,
		arg.IsRegular,
		arg.ID,
	)
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	Password string
	ID       string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}
