// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: wordkey_queries.sql

package db

import (
	"context"
	"database/sql"
)

const createWordKey = `-- name: CreateWordKey :execresult
INSERT INTO wordkeys (id, wordkey, active)
VALUES (?, ?, ?)
`

type CreateWordKeyParams struct {
	ID      string
	Wordkey string
	Active  bool
}

func (q *Queries) CreateWordKey(ctx context.Context, arg CreateWordKeyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createWordKey, arg.ID, arg.Wordkey, arg.Active)
}

const deactivateAllWordKeys = `-- name: DeactivateAllWordKeys :exec
UPDATE wordkeys
SET active = false
WHERE active = true
`

func (q *Queries) DeactivateAllWordKeys(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deactivateAllWordKeys)
	return err
}

const deleteWordKey = `-- name: DeleteWordKey :exec
DELETE FROM wordkeys WHERE id = ?
`

func (q *Queries) DeleteWordKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWordKey, id)
	return err
}

const getAllWordKeys = `-- name: GetAllWordKeys :many
SELECT id, wordkey, active, created_at
FROM wordkeys
ORDER BY created_at DESC
`

func (q *Queries) GetAllWordKeys(ctx context.Context) ([]Wordkey, error) {
	rows, err := q.db.QueryContext(ctx, getAllWordKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wordkey
	for rows.Next() {
		var i Wordkey
		if err := rows.Scan(
			&i.ID,
			&i.Wordkey,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWordKeyByActive = `-- name: GetWordKeyByActive :one
SELECT id, wordkey, active, created_at
FROM wordkeys
WHERE active = true
LIMIT 1
`

func (q *Queries) GetWordKeyByActive(ctx context.Context) (Wordkey, error) {
	row := q.db.QueryRowContext(ctx, getWordKeyByActive)
	var i Wordkey
	err := row.Scan(
		&i.ID,
		&i.Wordkey,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getWordKeyByID = `-- name: GetWordKeyByID :one
SELECT id, wordkey, active, created_at
FROM wordkeys
WHERE id = ?
`

func (q *Queries) GetWordKeyByID(ctx context.Context, id string) (Wordkey, error) {
	row := q.db.QueryRowContext(ctx, getWordKeyByID, id)
	var i Wordkey
	err := row.Scan(
		&i.ID,
		&i.Wordkey,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const updateWordKey = `-- name: UpdateWordKey :execresult
UPDATE wordkeys
SET wordkey = ?, active = ?
WHERE id = ?
`

type UpdateWordKeyParams struct {
	Wordkey string
	Active  bool
	ID      string
}

func (q *Queries) UpdateWordKey(ctx context.Context, arg UpdateWordKeyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWordKey, arg.Wordkey, arg.Active, arg.ID)
}
