// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: worker_queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createWorker = `-- name: CreateWorker :execresult
INSERT INTO workers (
  id, number, name, registration, birth_date,
  initiation_date, elevation_date, exaltation_date, affiliation_date, installation_date,
  emeritus_mason_date, provect_mason_date, image_url, deceased
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkerParams struct {
	ID                string
	Number            int32
	Name              string
	Registration      string
	BirthDate         time.Time
	InitiationDate    time.Time
	ElevationDate     time.Time
	ExaltationDate    time.Time
	AffiliationDate   time.Time
	InstallationDate  time.Time
	EmeritusMasonDate sql.NullTime
	ProvectMasonDate  sql.NullTime
	ImageUrl          string
	Deceased          bool
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createWorker,
		arg.ID,
		arg.Number,
		arg.Name,
		arg.Registration,
		arg.BirthDate,
		arg.InitiationDate,
		arg.ElevationDate,
		arg.ExaltationDate,
		arg.AffiliationDate,
		arg.InstallationDate,
		arg.EmeritusMasonDate,
		arg.ProvectMasonDate,
		arg.ImageUrl,
		arg.Deceased,
	)
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM workers WHERE id = ?
`

func (q *Queries) DeleteWorker(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorker, id)
	return err
}

const getAllWorkers = `-- name: GetAllWorkers :many
SELECT
  id, number, name, registration, birth_date,
  initiation_date, elevation_date, exaltation_date, affiliation_date, installation_date,
  emeritus_mason_date, provect_mason_date, image_url, deceased,
  created_at, updated_at
FROM workers
ORDER BY number ASC
`

func (q *Queries) GetAllWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, getAllWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Name,
			&i.Registration,
			&i.BirthDate,
			&i.InitiationDate,
			&i.ElevationDate,
			&i.ExaltationDate,
			&i.AffiliationDate,
			&i.InstallationDate,
			&i.EmeritusMasonDate,
			&i.ProvectMasonDate,
			&i.ImageUrl,
			&i.Deceased,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkerByID = `-- name: GetWorkerByID :one
SELECT
  id, number, name, registration, birth_date,
  initiation_date, elevation_date, exaltation_date, affiliation_date, installation_date,
  emeritus_mason_date, provect_mason_date, image_url, deceased,
  created_at, updated_at
FROM workers
WHERE id = ?
`

func (q *Queries) GetWorkerByID(ctx context.Context, id string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorkerByID, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Name,
		&i.Registration,
		&i.BirthDate,
		&i.InitiationDate,
		&i.ElevationDate,
		&i.ExaltationDate,
		&i.AffiliationDate,
		&i.InstallationDate,
		&i.EmeritusMasonDate,
		&i.ProvectMasonDate,
		&i.ImageUrl,
		&i.Deceased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkerByNumber = `-- name: GetWorkerByNumber :one
SELECT
  id, number, name, registration, birth_date,
  initiation_date, elevation_date, exaltation_date, affiliation_date, installation_date,
  emeritus_mason_date, provect_mason_date, image_url, deceased,
  created_at, updated_at
FROM workers
WHERE number = ?
`

func (q *Queries) GetWorkerByNumber(ctx context.Context, number int32) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorkerByNumber, number)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Name,
		&i.Registration,
		&i.BirthDate,
		&i.InitiationDate,
		&i.ElevationDate,
		&i.ExaltationDate,
		&i.AffiliationDate,
		&i.InstallationDate,
		&i.EmeritusMasonDate,
		&i.ProvectMasonDate,
		&i.ImageUrl,
		&i.Deceased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkerByRegistration = `-- name: GetWorkerByRegistration :one
SELECT
  id, number, name, registration, birth_date,
  initiation_date, elevation_date, exaltation_date, affiliation_date, installation_date,
  emeritus_mason_date, provect_mason_date, image_url, deceased,
  created_at, updated_at
FROM workers
WHERE registration = ?
`

func (q *Queries) GetWorkerByRegistration(ctx context.Context, registration string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorkerByRegistration, registration)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Name,
		&i.Registration,
		&i.BirthDate,
		&i.InitiationDate,
		&i.ElevationDate,
		&i.ExaltationDate,
		&i.AffiliationDate,
		&i.InstallationDate,
		&i.EmeritusMasonDate,
		&i.ProvectMasonDate,
		&i.ImageUrl,
		&i.Deceased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorker = `-- name: UpdateWorker :execresult
UPDATE workers
SET
  number = ?, name = ?, registration = ?, birth_date = ?,
  initiation_date = ?, elevation_date = ?, exaltation_date = ?, affiliation_date = ?,
  installation_date = ?, emeritus_mason_date = ?, provect_mason_date = ?,
  image_url = ?, deceased = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateWorkerParams struct {
	Number            int32
	Name              string
	Registration      string
	BirthDate         time.Time
	InitiationDate    time.Time
	ElevationDate     time.Time
	ExaltationDate    time.Time
	AffiliationDate   time.Time
	InstallationDate  time.Time
	EmeritusMasonDate sql.NullTime
	ProvectMasonDate  sql.NullTime
	ImageUrl          string
	Deceased          bool
	ID                string
}

func (q *Queries) UpdateWorker(ctx context.Context, arg UpdateWorkerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWorker,
		arg.Number,
		arg.Name,
		arg.Registration,
		arg.BirthDate,
		arg.InitiationDate,
		arg.ElevationDate,
		arg.ExaltationDate,
		arg.AffiliationDate,
		arg.InstallationDate,
		arg.EmeritusMasonDate,
		arg.ProvectMasonDate,
		arg.ImageUrl,
		arg.Deceased,
		arg.ID,
	)
}
